# Generated by Django 6.0.4 on 2026-04-28 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='default.png', upload_to='profile_pics/')),
                ('job_title', models.CharField(blank=True, help_text='e.g. Full Stack Developer', max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('website_url', models.URLField(blank=True, max_length=255)),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('twitter_username', models.CharField(blank=True, max_length=100)),
                ('instagram_username', models.CharField(blank=True, max_length=100)),
                ('facebook_username', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
